services:
  db:
    image: postgres:15
    container_name: hairdresser_db_container
    environment:
      POSTGRES_DB: hairdresser_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./src/resources/sql/initialization/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: always
volumes:
   db_data:
    driver: local

networks:
  zpabd_network: